/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudiobooksRouteImport } from './routes/audiobooks'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TeachingsRouteImport } from './routes/teachings'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiobooksRoute = AudiobooksRouteImport.update({
  id: '/audiobooks',
  path: '/audiobooks',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachingsRoute = TeachingsRouteImport.update({
  id: '/teachings',
  path: '/teachings',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audiobooks': typeof AudiobooksRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/teachings': typeof TeachingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/blog/': typeof BlogIndexRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audiobooks': typeof AudiobooksRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/teachings': typeof TeachingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/blog': typeof BlogIndexRoute
  '/books': typeof BooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audiobooks': typeof AudiobooksRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/teachings': typeof TeachingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/blog/': typeof BlogIndexRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audiobooks'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/teachings'
    | '/blog/$slug'
    | '/books/$bookId'
    | '/blog/'
    | '/books/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audiobooks'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/teachings'
    | '/blog/$slug'
    | '/books/$bookId'
    | '/blog'
    | '/books'
  id:
    | '__root__'
    | '/'
    | '/audiobooks'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/teachings'
    | '/blog/$slug'
    | '/books/$bookId'
    | '/blog/'
    | '/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudiobooksRoute: typeof AudiobooksRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  TeachingsRoute: typeof TeachingsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiobooks': {
      id: '/audiobooks'
      path: '/audiobooks'
      fullPath: '/audiobooks'
      preLoaderRoute: typeof AudiobooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachings': {
      id: '/teachings'
      path: '/teachings'
      fullPath: '/teachings'
      preLoaderRoute: typeof TeachingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudiobooksRoute: AudiobooksRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  TeachingsRoute: TeachingsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
